tcp  | tee -a $Outputs

diff --git a/A b/A
--- a/A
+++ b/A
@@ -12,7 +12,7 @@
 # http://xiaofd.win/onekey-ruisu.html
 # https://teddysun.com/489.html
 
-ScriptVersion=1.4.6
+ScriptVersion=1.4.7
 ScriptDate=2018.05.15
 
 # 颜色 -----------------------------------------------------------------------------------
@@ -549,7 +549,7 @@ wget --no-check-certificate -qO 1.deb https://github.com/Aniverse/BitTorrentClie
 wget --no-check-certificate -qO 2.deb https://github.com/Aniverse/BitTorrentClientCollection/raw/master/Linux%20Kernel/ServerSpeeder/linux-image-3.12-1.deb
 echo ` debconf-get-selections linux-image-3.12-1-amd64 | grep -C5 "keep the local version currently installed" | grep keep_current | sed "s/select/note/g"` | debconf-set-selections
 echo ` debconf-get-selections linux-headers-3.12-1-common | grep -C5 "keep the local version currently installed" | grep keep_current | sed "s/select/note/g"` | debconf-set-selections
-{ dpkg -i [12].deb >> $Outputs 2>&1 ; } || { { echo -e "\n  ${bold}${red}错误${jiacu} 安装 内核 失败！${normal}" 2>&1 | tee -a $Outputs 2>&1 ; } ; exit 1 ; }
+{ dpkg -i [12].deb >> $Outputs 2>&1 ; } || { echo -e "\n  ${bold}${red}错误${jiacu} 安装 内核 失败！${normal}" | tee -a $Outputs ; exit 1 ; }
 rm  -rf [12].deb ; echo ; }
 
 
@@ -558,7 +558,7 @@ rm  -rf [12].deb ; echo ; }
 function _debian_serverspeeder_kernel_316() {
 wget --no-check-certificate -qO 1.deb https://github.com/Aniverse/BitTorrentClientCollection/raw/master/Linux%20Kernel/ServerSpeeder/linux-image-3.16.0-4.deb
 echo ` debconf-get-selections linux-image-3.16.0-4-amd64 | grep -C5 "keep the local version currently installed" | grep keep_current | sed "s/select/note/g"` | debconf-set-selections
-{ dpkg -i 1.deb >> $Outputs 2>&1 ; } || { { echo -e "\n  ${bold}${red}错误${jiacu} 安装 内核 失败！${normal}" 2>&1 | tee -a $Outputs 2>&1 ; } ; exit 1 ; }
+{ dpkg -i 1.deb >> $Outputs 2>&1 ; } || { echo -e "\n  ${bold}${red}错误${jiacu} 安装 内核 失败！${normal}" | tee -a $Outputs ; exit 1 ; }
 rm  -rf 1.deb ; }
 
 
@@ -571,7 +571,7 @@ wget --no-check-certificate -qO 3.deb https://github.com/Aniverse/BitTorrentClie
 echo ` debconf-get-selections linux-image-4.4.0-47-generic | grep -C5 "keep the local version currently installed" | grep keep_current | sed "s/select/note/g"` | debconf-set-selections
 echo ` debconf-get-selections linux-headers-4.4.0-47 | grep -C5 "keep the local version currently installed" | grep keep_current | sed "s/select/note/g"` | debconf-set-selections
 echo ` debconf-get-selections linux-headers-4.4.0-47-generic | grep -C5 "keep the local version currently installed" | grep keep_current | sed "s/select/note/g"` | debconf-set-selections
-{ dpkg -i [123].deb >> $Outputs 2>&1 ; } || { { echo -e "\n  ${bold}${red}错误${jiacu} 安装 内核 失败！${normal}" 2>&1 | tee -a $Outputs 2>&1 ; } ; exit 1 ; }
+{ dpkg -i [123].deb >> $Outputs 2>&1 ; } || { echo -e "\n  ${bold}${red}错误${jiacu} 安装 内核 失败！${normal}" | tee -a $Outputs ; exit 1 ; }
 rm  -rf [123].deb ; }
 
 
@@ -584,7 +584,7 @@ wget --no-check-certificate -qO 3.deb https://github.com/Aniverse/SSKernel/raw/m
 echo ` debconf-get-selections linux-image-3.16.0-43-generic | grep -C5 "keep the local version currently installed" | grep keep_current | sed "s/select/note/g"` | debconf-set-selections
 echo ` debconf-get-selections linux-image-extra-3.16.0-43-generic | grep -C5 "keep the local version currently installed" | grep keep_current | sed "s/select/note/g"` | debconf-set-selections
 echo ` debconf-get-selections linux-headers-3.16.0-43-generic | grep -C5 "keep the local version currently installed" | grep keep_current | sed "s/select/note/g"` | debconf-set-selections
-{ dpkg -i [123].deb >> $Outputs 2>&1 ; } || { { echo -e "\n  ${bold}${red}错误${jiacu} 安装 内核 失败！${normal}" 2>&1 | tee -a $Outputs 2>&1 ; } ; exit 1 ; }
+{ dpkg -i [123].deb >> $Outputs 2>&1 ; } || { echo -e "\n  ${bold}${red}错误${jiacu} 安装 内核 失败！${normal}" | tee -a $Outputs ; exit 1 ; }
 rm  -rf [123].deb ; }
 
 
@@ -594,13 +594,13 @@ function _ubuntu_serverspeeder_kernel_repo() {
 sed -i '/deb http:\/\/security.ubuntu.com\/ubuntu trusty-security main/'d /etc/apt/sources.list
 echo "deb http://security.ubuntu.com/ubuntu trusty-security main" >> /etc/apt/sources.list
 echo -ne "\n  ${bold}添加源，更新 ...  ${normal}"
-{ apt-get update >> $Outputs 2>&1 ; } && { echo "${green}${bold}完成${normal}" 2>&1 | tee -a $Outputs ; }
-echo -ne "\n  ${bold}安装内核 ...  ${normal}" 2>&1 | tee -a $Outputs 2>&1
-apt-get -y install linux-image-extra-$kernelver linux-image-$kernelver linux-headers-$kernelver >> $Outputs 2>&1 && { echo "${green}${bold}完成${normal}" 2>&1 | tee -a $Outputs 2>&1 ; }
-[[ ! ` dpkg -l | grep linux-image-$kernelver ` ]] && { { echo "${bold}${red}失败${normal}" 2>&1 | tee -a $Outputs 2>&1 ; } ; exit 1 ; }
+{ apt-get update >> $Outputs 2>&1 ; } && { echo "${green}${bold}完成${normal}" | tee -a $Outputs ; }
+echo -ne "\n  ${bold}安装内核 ...  ${normal}" | tee -a $Outputs
+apt-get -y install linux-image-extra-$kernelver linux-image-$kernelver linux-headers-$kernelver >> $Outputs 2>&1 && { echo "${green}${bold}完成${normal}" | tee -a $Outputs ; }
+[[ ! ` dpkg -l | grep linux-image-$kernelver ` ]] && { echo "${bold}${red}失败${normal}" | tee -a $Outputs ; exit 1 ; }
 sed -i '/deb http:\/\/security.ubuntu.com\/ubuntu trusty-security main/'d /etc/apt/sources.list
-echo -ne "\n  ${bold}删除源，更新 ...  ${normal}" 2>&1 | tee -a $Outputs 2>&1
-{ apt-get update >> $Outputs 2>&1 ; } && { echo "${green}${bold}完成${normal}" 2>&1 | tee -a $Outputs ; } ; }
+echo -ne "\n  ${bold}删除源，更新 ...  ${normal}" | tee -a $Outputs
+{ apt-get update >> $Outputs 2>&1 ; } && { echo "${green}${bold}完成${normal}" | tee -a $Outputs ; } ; }
 
 
 
@@ -608,8 +608,8 @@ echo -ne "\n  ${bold}删除源，更新 ...  ${normal}" 2>&1 | tee -a $Outputs 2
 function _ubuntu_serverspeeder_updategrub() {
 sed -i 's/GRUB_DEFAULT=.*/GRUB_DEFAULT="Advanced options for Ubuntu>Ubuntu, with Linux kernelver"/' /etc/default/grub
 sed -i "s/kernelver/$kernelver/" /etc/default/grub
-echo -ne "\n  ${bold}更新引导 ...  " 2>&1 | tee -a $Outputs 2>&1
-{ update-grub >> $Outputs 2>&1 ; } && { echo "${green}${bold}完成${normal}" 2>&1 | tee -a $Outputs ; } ; }
+echo -ne "\n  ${bold}更新引导 ...  " | tee -a $Outputs
+{ update-grub >> $Outputs 2>&1 ; } && { echo "${green}${bold}完成${normal}" | tee -a $Outputs ; } ; }
 
 
 
@@ -664,38 +664,39 @@ update-grub >> $Outputs 2>&1 && { echo "${green}${bold}完成${normal}" | tee -a
 function _check_essential() {
 
 [[ ! `dpkg -l | grep libelf-dev` ]] && { echo -ne "\n  ${bold}安装 libelf-dev ...${normal} " | tee -a $Outputs ; apt-get install -y libelf1 libelf-dev >> $Outputs 2>&1 ; echo
-[[ ! `dpkg -l | grep libelf-dev` ]] && { echo -e  "\n$  ${red}错误${bold} 安装 libelf-dev 失败！${normal}" ; exit 1 ; } ; }
+[[ ! `dpkg -l | grep libelf-dev` ]] && { echo -e  "\n$  ${red}错误${bold} 安装 libelf-dev 失败！${normal}" | tee -a $Outputs ; exit 1 ; } ; }
 
 if [[ $CODENAME == stretch ]]; then
-    [[ ! `dpkg -l | grep libssl1.0.0` ]] && { echo -ne "\n  {bold}安装 libssl1.0.0 ...${normal} " 2>&1 | tee -a $Outputs 2>&1
+    [[ ! `dpkg -l | grep libssl1.0.0` ]] && {
+    echo -ne "\n  {bold}安装 libssl1.0.0 ...${normal} " | tee -a $Outputs
     echo -e "\ndeb http://ftp.hk.debian.org/debian jessie main\c" >> /etc/apt/sources.list
     apt-get update >> $Outputs 2>&1
     apt-get install -y libssl1.0.0 >> $Outputs 2>&1
     sed  -i '/deb http:\/\/ftp\.hk\.debian\.org\/debian jessie main/d' /etc/apt/sources.list
     apt-get update >> $Outputs 2>&1 ; echo
-    [[ ! `dpkg -l | grep libssl1.0.0` ]] && { echo -e "\n  ${red}错误${bold} 安装 libssl1.0.0 失败！${normal}" ; exit 1 ; } ; }
+    [[ ! `dpkg -l | grep libssl1.0.0` ]] && { echo -e "\n  ${red}错误${bold} 安装 libssl1.0.0 失败！${normal}" | tee -a $Outputs ; exit 1 ; } ; }
 else
     [[ ! `dpkg -l | grep libssl1.0.0` ]] && { echo -ne "\n  ${bold}安装 libssl1.0.0 ...${normal} " | tee -a $Outputs ; apt-get install -y libssl1.0.0 >> $Outputs 2>&1 ; echo
-    [[ ! `dpkg -l | grep libssl1.0.0` ]] && { echo -e  "\n$  ${red}错误${bold} 安装 libssl1.0.0 失败！${normal}" ; exit 1 ; } ; }
+    [[ ! `dpkg -l | grep libssl1.0.0` ]] && { echo -e  "\n$  ${red}错误${bold} 安装 libssl1.0.0 失败！${normal}" | tee -a $Outputs ; exit 1 ; } ; }
 fi
 
 which make >> $Outputs 2>&1 ; [ $? -ne '0' ] && { echo -ne "\n  ${bold}安装 make ...${normal} "    | tee -a $Outputs  ; apt-get install -y make >> $Outputs 2>&1 ; echo
-which make >> $Outputs 2>&1 ; [ $? -ne '0' ] && { echo -e  "\n  ${red}错误${bold} 安装 make 失败！${normal}" ; exit 1 ; } ; }
+which make >> $Outputs 2>&1 ; [ $? -ne '0' ] && { echo -e  "\n  ${red}错误${bold} 安装 make 失败！${normal}" | tee -a $Outputs ; exit 1 ; } ; }
 
 which awk  >> $Outputs 2>&1 ; [ $? -ne '0' ] && { echo -ne "\n  ${bold}安装 awk ...${normal} "     | tee -a $Outputs  ; apt-get install -y gawk >> $Outputs 2>&1 ; echo
-which awk  >> $Outputs 2>&1 ; [ $? -ne '0' ] && { echo -e  "\n  ${red}错误${bold} 安装 awk 失败！${normal}"  ; exit 1 ; } ; }
+which awk  >> $Outputs 2>&1 ; [ $? -ne '0' ] && { echo -e  "\n  ${red}错误${bold} 安装 awk 失败！${normal}" | tee -a $Outputs  ; exit 1 ; } ; }
 
 which gcc  >> $Outputs 2>&1 ; [ $? -ne '0' ] && { echo -ne "\n  ${bold}安装 gcc ...${normal} "     | tee -a $Outputs  ; apt-get install -y gcc  >> $Outputs 2>&1 ; echo
-which gcc  >> $Outputs 2>&1 ; [ $? -ne '0' ] && { echo -e  "\n  ${red}错误${bold} 安装 gcc 失败！${normal}"  ; exit 1 ; } ; }
+which gcc  >> $Outputs 2>&1 ; [ $? -ne '0' ] && { echo -e  "\n  ${red}错误${bold} 安装 gcc 失败！${normal}" | tee -a $Outputs  ; exit 1 ; } ; }
 
 gcc_ok=0 ; gcc_ver=` gcc --version | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' | head -n1 `
 gcc_ver_1=` echo $gcc_ver | awk -F. '{print $1}' ` ; gcc_ver_2=` echo $gcc_ver | awk -F. '{print $2}' `
 [[ -n $gcc_ver_1 ]] && [[ $gcc_ver_1 -gt 4 ]] && gcc_ok=1
 [[ $gcc_ver_1 == 4 ]] && [[ -n $gcc_ver_2 ]] && [[ $gcc_ver_2 -ge 9 ]] && gcc_ok=1
-[[ $gcc_ok == 0 ]] && { echo -e "\n  ${red}错误${bold} gcc 版本低于 4.9！${normal}" | tee -a $Outputs 2>&1; exit 1 ; }
+[[ $gcc_ok == 0 ]] && { echo -e "\n  ${red}错误${bold} gcc 版本低于 4.9！${normal}" | tee -a $Outputs ; exit 1 ; }
 
-[[ ! `dpkg -l | grep build-essential` ]] && { echo -ne "\n  ${bold}安装 build-essential ...${normal} "  ; apt-get install -y build-essential >> $Outputs 2>&1 ; echo
-[[ ! `dpkg -l | grep build-essential` ]] && { echo -e  "\n  ${red}错误${bold} 安装 build-essential  失败！${normal}" ; exit 1 ; } ; } ; }
+[[ ! `dpkg -l | grep build-essential` ]] && { echo -ne "\n  ${bold}安装 build-essential ...${normal} " | tee -a $Outputs  ; apt-get install -y build-essential >> $Outputs 2>&1 ; echo
+[[ ! `dpkg -l | grep build-essential` ]] && { echo -e  "\n  ${red}错误${bold} 安装 build-essential  失败！${normal}" | tee -a $Outputs ; exit 1 ; } ; } ; }
 
 
 
@@ -765,7 +766,7 @@ function _check_headers() {
 required_version=$(  uname -r | cut  -d- -f1  )
 headers_exits=`  dpkg -l | grep linux-headers | awk '{print $2}' | awk -F '-' '{print $3}' | grep $required_version | wc -l  `
 if [[ $headers_exits == 0 ]]; then
-    echo -e "  ${red}错误${jiacu} 没有安装与内核对应的头文件，先尝试安装内核头文件 ...${normal} "
+    echo -e "  ${red}错误${jiacu} 没有安装与内核对应的头文件，先尝试安装内核头文件 ...${normal} " | tee -a $Outputs
     _install_required_headers
 fi ; }
 
@@ -778,7 +779,8 @@ while [[ -z "${required_version}" ]]; do
     echo -ne "\n  ${yellow}输入你想要的内核版本号 （敲回车则使用最新内核）：${normal}" ; read -e required_version
     [[ -z "${required_version}" ]] && required_version=`  wget -qO- http://kernel.ubuntu.com/~kernel-ppa/mainline/ | awk -F'\"v' '/v[4-9]./{print $2}' | cut -d/ -f1 | grep -v -  | sort -V | tail -1  `
     [[ -z ` wget -qO- http://kernel.ubuntu.com/~kernel-ppa/mainline/v${required_version}/ ` ]] && { echo -e "\n  ${red}错误${jiacu} 这个内核不存在或无法使用本脚本下载，请重新输入！${normal}" ; unset required_version ; }
-done ; }
+done
+echo -ne "\n  ${yellow}输入你想要的内核版本号 （敲回车则使用最新内核）：$required_version ${normal}" >> $Outputs ; }
 
 
 
@@ -789,10 +791,10 @@ digit_ver_headers=`dpkg -l | grep linux-headers | awk '{print $2}' | awk -F '-' 
 [[ $DeBUG == 1 ]] && echo "${required_version}"
 
 if [[ -z $digit_ver_image ]]; then _install_required_kernel
-else echo -e "\n  ${bold}${green}$required_version${jiacu} 内核已安装 ...${normal}\n" ; fi
+else echo -e "\n  ${bold}${green}$required_version${jiacu} 内核已安装 ...${normal}\n" | tee -a $Outputs ; fi
 
 if [[ -z $digit_ver_headers ]]; then _install_required_headers
-else echo -e "\n  ${bold}${green}$required_version${jiacu} 头文件已安装 ...${normal}\n" ; fi ; }
+else echo -e "\n  ${bold}${green}$required_version${jiacu} 头文件已安装 ...${normal}\n" | tee -a $Outputs ; fi ; }
 
 
 
@@ -803,8 +805,8 @@ image_name=`wget -qO- http://kernel.ubuntu.com/~kernel-ppa/mainline/v${required_
 image_url="http://kernel.ubuntu.com/~kernel-ppa/mainline/v${required_version}/${image_name}"
 
 echo -ne "\n  ${bold}安装 ${green}$required_version${jiacu} 内核 ... ${normal}"
-wget -qO kernel.deb $image_url || { echo -e "\n  ${red}错误${jiacu} 内核 下载失败！${normal}\n" ; exit 1 ; }
-dpkg -i kernel.deb >> $Outputs 2>&1 || { echo -e "\n  ${red}错误${jiacu} 内核 安装失败！${normal}\n" ; exit 1 ; }
+wget -qO kernel.deb $image_url || { echo -e "\n  ${red}错误${jiacu} 内核 下载失败！${normal}\n" | tee -a $Outputs ; exit 1 ; }
+dpkg -i kernel.deb >> $Outputs 2>&1 || { echo -e "\n  ${red}错误${jiacu} 内核 安装失败！${normal}\n" | tee -a $Outputs ; exit 1 ; }
 
 rm kernel.deb ; }
 
@@ -818,12 +820,12 @@ headers_bit_name=`  wget -qO- http://kernel.ubuntu.com/~kernel-ppa/mainline/v${r
 headers_bit_url="http://kernel.ubuntu.com/~kernel-ppa/mainline/v${required_version}/${headers_bit_name}"
 
 echo -ne "\n  ${bold}安装 ${green}$required_version${jiacu} headers_all ... ${normal}"
-wget -qO headers1.deb $headers_all_url || { echo -e "\n  ${red}错误${jiacu} headers_all 下载失败！${normal}\n" ; exit 1 ; }
-dpkg -i headers1.deb >> $Outputs 2>&1  || { echo -e "\n  ${red}错误${jiacu} headers_all 安装失败！${normal}\n" ; exit 1 ; }
+wget -qO headers1.deb $headers_all_url || { echo -e "\n  ${red}错误${jiacu} headers_all 下载失败！${normal}\n" | tee -a $Outputs ; exit 1 ; }
+dpkg -i headers1.deb >> $Outputs 2>&1  || { echo -e "\n  ${red}错误${jiacu} headers_all 安装失败！${normal}\n" | tee -a $Outputs ; exit 1 ; }
 
 echo -ne "\n  ${bold}安装 ${green}$required_version${jiacu} headers ... ${normal}"
-wget -qO headers2.deb $headers_bit_url || { echo -e "\n  ${red}错误${jiacu} headers 下载失败！${normal}\n"     ; exit 1 ; }
-dpkg -i headers2.deb >> $Outputs 2>&1  || { echo -e "\n  ${red}错误${jiacu} headers_all 安装失败！${normal}\n" ; exit 1 ; }
+wget -qO headers2.deb $headers_bit_url || { echo -e "\n  ${red}错误${jiacu} headers 下载失败！${normal}\n"     | tee -a $Outputs ; exit 1 ; }
+dpkg -i headers2.deb >> $Outputs 2>&1  || { echo -e "\n  ${red}错误${jiacu} headers_all 安装失败！${normal}\n" | tee -a $Outputs ; exit 1 ; }
 rm headers1.deb headers2.deb ; }
 
 
@@ -849,14 +851,14 @@ for ddd in debconf-set-selections debconf-get-selections ; do
 if [ $kernel_total > 1 ]; then
     for (( integer = 1 ; integer <= ${kernel_total} ; integer++ )) ; do
         kernel_tobe_del=` dpkg -l | grep -E linux-[image,headers] | awk '{print $2}' | grep -v "${kernel_version}" | head -${integer} `
-        echo -ne "Removing ${kernel_tobe_del} ... "
+        echo -ne "Removing ${kernel_tobe_del} ... " | tee -a $Outputs
         echo `debconf-get-selections ${deb_del} | grep removing-running-kernel | grep $running_kernel | sed s/true/false/` | debconf-set-selections
-        apt-get -y purge $kernel_tobe_del >> $Outputs 2>&1 && echo "$(tput setaf 2)DONE$(tput sgr0)" || echo "$(tput setaf 1)FAILED$(tput sgr0)"
+        apt-get -y purge $kernel_tobe_del >> $Outputs 2>&1 && { echo "$(tput setaf 2)DONE$(tput sgr0)" | tee -a $Outputs ; } || { echo "$(tput setaf 1)FAILED$(tput sgr0)" | tee -a $Outputs ; }
     done
 fi
 
-echo -ne "\n  ${bold}更新引导 ...  "
-update-grub >> $Outputs 2>&1 && echo "${green}完成${normal}" ; }
+echo -ne "\n  ${bold}更新引导 ...  " | tee -a $Outputs
+update-grub >> $Outputs 2>&1 && echo "${green}完成${normal}" | tee -a $Outputs ; }
 
 
 
