tcp / askcontinue, selected kernel, output

diff --git a/A b/A
--- a/A
+++ b/A
@@ -34,6 +34,7 @@ SysSupport=0 ; DeBUG=0
 [[ $1 == -d ]] && DeBUG=1
 
 KernelBit=` getconf LONG_BIT `
+[[ $KernelBit == 32 ]] && KernelBitVer=i386 ; [[ $KernelBit == 64 ]] && KernelBitVer=amd64
 DISTRO=`  awk -F'[= "]' '/PRETTY_NAME/{print $3}' /etc/os-release | tr 'A-Z' 'a-z'  `
 DISTROU=`  awk -F'[= "]' '/PRETTY_NAME/{print $3}' /etc/os-release  `
 CODENAME=`  cat /etc/os-release | grep VERSION= | tr '[A-Z]' '[a-z]' | sed 's/\"\|(\|)\|[0-9.,]\|version\|lts//g' | awk '{print $2}'  `
@@ -117,9 +118,8 @@ echo -e  "  ${green}(03) ${jiacu}安装 魔改 BBR (nanqinlang)"
 echo -e  "  ${green}(04) ${jiacu}安装 锐速"
 echo -e  "  ${green}(21) ${jiacu}卸载 BBR"
 echo -e  "  ${green}(22) ${jiacu}卸载 锐速"
-# echo -e  "  ${green}(11) ${jiacu}安装 最新内核"
-# echo -e  "  ${green}(12) ${jiacu}安装 指定内核"
-# echo -e  "  ${green}(13) ${jiacu}安装 锐速内核"
+echo -e  "  ${green}(11) ${jiacu}安装 指定内核"
+# echo -e  "  ${green}(12) ${jiacu}安装 特定的锐速内核"
 echo -e  "  ${green}(99) ${jiacu}返回\n"
 rm -rf /tmp/system_kernel_list ; }
 
@@ -140,6 +140,8 @@ case $response in
             _nqlbbr_install ;;
     4 | 04) # 安装 锐速
             _ss_install ;;
+        11) # 安装 最新内核
+            _selected_kernel_install ;;
         21) # 卸载 BBR
             _bbr_uninstall ;;
         22) # 卸载 锐速
@@ -172,6 +174,7 @@ if [[ $BBRKernel == "${green}是${jiacu}" ]]; then
     if [[ ` sysctl net.ipv4.tcp_available_congestion_control | awk '{print $3}' ` == bbr ]]; then echo -e "\n  ${bold}BBR 已启用 ...\n${normal}"
     else echo -e "\n  ${bold}${red}错误 BBR 开启失败！${normal}\n" ; exit 1 ; fi
 else
+    _ask_continue2
     echo -e "\n  ${bold}当前内核不支持 BBR，需要安装 ${green}4.11.12${jiacu} 内核以启用 BBR ...${normal} "
     _online_ubuntu_bbr_firmware
     _bbr_kernel_4_11_12
@@ -181,6 +184,7 @@ else
 fi ; }
 
 
+
 # 安装 Yankee版魔改 BBR
 function _ykbbr_install() {
 
@@ -188,6 +192,7 @@ function _ykbbr_install() {
 
 if [[ $YKKernel == "${green}是${jiacu}" ]]; then
     echo -ne "\n  ${bold}理论上当前内核已支持 ${green}Yankee${jiacu} 版魔改 BBR，安装并启用魔改 BBR ...${normal} "
+    _check_headers
     _check_essential
     _bbr_tsunami
     bbrname=tsunami
@@ -195,6 +200,7 @@ if [[ $YKKernel == "${green}是${jiacu}" ]]; then
     if [[ ` sysctl net.ipv4.tcp_available_congestion_control | awk '{print $3}' ` == tsunami ]]; then echo -e "\n  ${bold}已开启 ${green}Yankee 版魔改 BBR${jiacu} ...${normal}\n"
     else echo -e "\n  ${bold}${red}错误 ${green}Yankee 版魔改 BBR${jiacu} 开启失败！${normal}\n" ; exit 1 ; fi
 else
+    _ask_continue2
     echo -e "\n  ${bold}当前内核不支持 ${green}Yankee${jiacu} 版魔改 BBR，需要安装 ${green}4.11.12${jiacu} 内核 ...${normal}"
     _online_ubuntu_bbr_firmware
     _check_essential
@@ -216,6 +222,7 @@ function _nqlbbr_install() {
 
 if [[ $NQLKernel == "${green}是${jiacu}" ]]; then
     echo -ne "\n  ${bold}理论上当前内核已支持 ${green}南琴浪${jiacu} 版魔改 BBR，安装并启用魔改 BBR ...${normal} "
+    _check_headers
     _check_essential
     _bbr_nanqinlang
     bbrname=nanqinlang
@@ -223,6 +230,7 @@ if [[ $NQLKernel == "${green}是${jiacu}" ]]; then
     if [[ ` sysctl net.ipv4.tcp_available_congestion_control | awk '{print $3}' ` == nanqinlang ]]; then echo -e "\n  ${bold}已开启 ${green}南琴浪${jiacu} 版魔改 BBR ...${normal}\n"
     else echo -e "\n  ${bold}${red}错误 ${green}南琴浪 版魔改 BBR${jiacu} 开启失败！${normal}\n" ; exit 1 ; fi
 else
+    _ask_continue2
     echo -e "\n  ${bold}当前内核不支持 ${green}南琴浪${jiacu} 版魔改 BBR，需要安装 ${green}4.11.12${jiacu} 内核 ...${normal} "
     _online_ubuntu_bbr_firmware
     _check_essential
@@ -243,6 +251,7 @@ if [[ $SSKernel == "${green}是${jiacu}" ]]; then
     echo -e "\n  ${bold}理论上当前内核已支持 ${green}锐速${jiacu}，直接安装 ... ${normal} "
     _serverspeeder_direct_install
 elif [[ $SSKernel == "${red}否${jiacu}" ]] && [[ $DISTRO == ubuntu ]]; then
+    _ask_continue2
     echo -ne "\n  ${bold}当前内核不支持 锐速，安装 ${green}3.16.0-43${jiacu} 内核 ... ${normal} "
     kernelver=3.16.0-43-generic
     _ubuntu_serverspeeder_kernel_repo
@@ -250,6 +259,7 @@ elif [[ $SSKernel == "${red}否${jiacu}" ]] && [[ $DISTRO == ubuntu ]]; then
     _serverspeeder_autoinstall_after_reboot
     [[ ! $DeBUG == 1 ]] && echo -ne "\n  ${bold}即将重启系统，重启后会自动安装 ${green}锐速${jiacu} ... ${normal}" && reboot
 elif [[ $SSKernel == "${red}否${jiacu}" ]] && [[ $CODENAME == jessie ]]; then
+    _ask_continue2
     echo -ne "\n  ${bold}当前内核不支持 锐速，安装 ${green}3.12.1${jiacu} 内核 ... ${normal} "
     kernel_version=3.12-1
     _debian_serverspeeder_kernel_312
@@ -257,6 +267,7 @@ elif [[ $SSKernel == "${red}否${jiacu}" ]] && [[ $CODENAME == jessie ]]; then
     _serverspeeder_autoinstall_after_reboot
     [[ ! $DeBUG == 1 ]] && echo -ne "\n  ${bold}即将重启系统，重启后会自动安装 ${green}锐速${jiacu} ... ${normal}" && reboot
 elif [[ $SSKernel == "${red}否${jiacu}" ]] && [[ $CODENAME == stretch ]]; then
+    _ask_continue2
     echo -ne "\n  ${bold}当前内核不支持 锐速，安装 ${green}3.16.0-4${jiacu} 内核 ... ${normal} "
     kernel_version=3.16.0-4
     _debian_serverspeeder_kernel_316
@@ -290,6 +301,17 @@ esac
 tcp_control=` sysctl net.ipv4.tcp_available_congestion_control | awk '{print $3}' `
 if [[ $tcp_control =~ ("nanqinlang"|"tsunami"|"bbr"|"bbr_powered") ]]; then bbrname=$tcp_control ; _disable_bbr ; echo -e "  ${bold}${red}已卸载 BBR，但安装的内核仍保留${normal}\n"
 else echo -e "\n  ${bold}${red}错误 ${jiacu}你并没有使用本脚本安装 BBR ...${normal}\n" ; _read_response ; fi ; }
+
+
+
+# 安装 指定内核（BBR）
+function _selected_kernel_install() {
+_get_version
+_install_required_kernel
+_install_required_headers
+kernel_version=$required_version
+_delete_kernel ; }
+
 
 
 
@@ -465,7 +487,7 @@ function _online_ubuntu_bbr_firmware() {
 mkdir -p /lib/firmware/bnx2
 if [[ ! -f /lib/firmware/bnx2/fw.lock ]]; then
     touch /lib/firmware/bnx2/fw.lock
-    echo -e "  ${bold}下载可能缺少的固件 ... ${normal}\n"
+    echo -e "\n  ${bold}下载可能缺少的固件 ... ${normal}"
     wget -qO /lib/firmware/bnx2/bnx2-mips-06-6.2.3.fw https://github.com/Aniverse/BitTorrentClientCollection/raw/master/Linux%20Firmware/bnx2-mips-06-6.2.3.fw
     wget -qO /lib/firmware/bnx2/bnx2-mips-09-6.2.1b.fw https://github.com/Aniverse/BitTorrentClientCollection/raw/master/Linux%20Firmware/bnx2-mips-09-6.2.1b.fw
     wget -qO /lib/firmware/bnx2/bnx2-rv2p-09ax-6.0.17.fw https://github.com/Aniverse/BitTorrentClientCollection/raw/master/Linux%20Firmware/bnx2-rv2p-09ax-6.0.17.fw
@@ -483,34 +505,9 @@ wget --no-check-certificate -qO 2.deb https://github.com/Aniverse/BitTorrentClie
 wget --no-check-certificate -qO 3.deb https://github.com/Aniverse/BitTorrentClientCollection/raw/master/Linux%20Kernel/BBR/linux-image-4.11.12-generic-amd64.deb
 dpkg -i [123].deb > /dev/null 2>&1 || { echo -e "\n  ${bold}${red}错误${jiacu} 安装 内核 失败！${normal}" ; exit 1 ; }
 rm -rf [123].deb ; echo
-echo -ne "  ${bold}更新引导 ...  "
+echo -ne "\n  ${bold}更新引导 ...  "
 update-grub > /dev/null 2>&1 && echo "${green}${bold}完成${normal}"
 echo ; }
-
-
-
-# 检查最新版内核（For BBR）
-function _get_latest_version() {
-latest_version=$(wget -qO- http://kernel.ubuntu.com/~kernel-ppa/mainline/ | awk -F'\"v' '/v[4-9]./{print $2}' | cut -d/ -f1 | grep -v -  | sort -V | tail -1)
-[ -z ${latest_version} ] && return 1
-deb_name=$(wget -qO- http://kernel.ubuntu.com/~kernel-ppa/mainline/v${latest_version}/ | grep "linux-image" | grep "generic" | awk -F'\">' '/amd64.deb/{print $2}' | cut -d'<' -f1 | head -1)
-deb_kernel_url="http://kernel.ubuntu.com/~kernel-ppa/mainline/v${latest_version}/${deb_name}"
-deb_kernel_name="linux-image-${latest_version}-amd64.deb"
-[ ! -z ${deb_name} ] && return 0 || return 1 ; }
-
-
-
-# 下载、安装 最新版内核（For BBR）
-function _install_latest_kernel() {
-_get_latest_version
-[ $? -ne 0 ] && echo -e "\n  ${red}${bold}错误${jiacu} 获取最新内核失败" && exit 1
-wget -c -t3 -T60 -qO "${deb_kernel_name}" "${deb_kernel_url}"
-if [ $? -ne 0 ]; then echo -e "\n  ${red}${bold}错误${jiacu} 下载 ${deb_kernel_name} 失败，请检查！" ; exit 1 ; fi
-
-dpkg -i "${deb_kernel_name}" > /dev/null 2>&1
-rm -fv "${deb_kernel_name}"
-echo -ne "${bold}更新引导 ...  "
-update-grub > /dev/null 2>&1 && echo "${green}完成${normal}" ; }
 
 
 
@@ -607,6 +604,68 @@ sysctl -p > /dev/null 2>&1 ; }
 
 
 
+# 检查 headers
+function _check_headers() {
+required_version=$(  uname -r | cut  -d- -f1  )
+headers_exits=`  dpkg -l | grep linux-headers | awk '{print $2}' | awk -F '-' '{print $3}' | grep $required_version | wc -l  `
+if [[ $headers_exits == 0 ]]; then
+    echo -e "\n  ${red}错误${jiacu} 没有安装与内核对应的头文件，先尝试安装内核头文件 ...${normal} "
+    _install_required_headers
+fi ; }
+
+
+
+# 询问版本（BBR）
+function _get_version() {
+unset required_version
+while [[ -z "${required_version}" ]]; do
+    echo -ne "\n  输入你想要的内核版本号 （敲回车则使用最新内核）：" ; read -e required_version
+    [[ -z "${required_version}" ]] && required_version=`  wget -qO- http://kernel.ubuntu.com/~kernel-ppa/mainline/ | awk -F'\"v' '/v[4-9]./{print $2}' | cut -d/ -f1 | grep -v -  | sort -V | tail -1  `
+    [[ -z ` wget -qO- http://kernel.ubuntu.com/~kernel-ppa/mainline/v${required_version}/ ` ]] && { echo -e "\n  ${red}错误${jiacu} 这个内核不存在或无法使用本脚本下载，请重新输入！${normal}" ; unset required_version ; }
+done
+
+digit_ver_image=`dpkg -l | grep linux-image | awk '{print $2}' | awk -F '-' '{print $3}' | grep "${required_version}"`
+digit_ver_headers=`dpkg -l | grep linux-headers | awk '{print $2}' | awk -F '-' '{print $3}' | grep "${required_version}"`
+
+if [[ -z $digit_ver_image ]]; then _install_required_kernel
+else echo -e "\n  ${bold}${green}$required_version${jiacu} 内核已安装 ...${normal}\n" ; fi
+
+if [[ -z $digit_ver_headers ]]; then _install_required_headers
+else echo -e "\n  ${bold}${green}$required_version${jiacu} 头文件已安装 ...${normal}\n" ; fi ; }
+
+
+
+# 安装自选版本的内核
+function _install_required_kernel() {
+image_name=`wget -qO- http://kernel.ubuntu.com/~kernel-ppa/mainline/v${required_version}/ | grep "linux-image" | grep "lowlatency" | awk -F'\">' '/amd64.deb/{print $2}' | cut -d'<' -f1 | head -1`
+image_url="http://kernel.ubuntu.com/~kernel-ppa/mainline/v${required_version}/${image_name}"
+
+echo -ne "\n  ${bold}安装 ${green}$required_version${jiacu} 内核 ... ${normal}"
+wget -qO kernel.deb $kernel_url || { echo -e "\n  ${red}错误${jiacu} 内核 下载失败！${normal}\n" ; exit 1 ; }
+dpkg -i kernel.deb || { echo -e "\n  ${red}错误${jiacu} 内核 安装失败！${normal}\n" ; exit 1 ; }
+
+rm kernel.deb ; }
+
+
+
+# 安装自选版本的头文件
+function _install_required_headers() {
+headers_all_name=`  wget -qO- http://kernel.ubuntu.com/~kernel-ppa/mainline/v${required_version}/ | grep "linux-headers" | awk -F'\">' '/all.deb/{print $2}' | cut -d'<' -f1 | head -1  `
+headers_all_url="http://kernel.ubuntu.com/~kernel-ppa/mainline/v${required_version}/${headers_all_name}"
+headers_bit_name=`  wget -qO- http://kernel.ubuntu.com/~kernel-ppa/mainline/v${required_version}/ | grep "linux-headers" | grep "lowlatency" | awk -F'\">' '/amd64.deb/{print $2}' | cut -d'<' -f1 | head -1  `
+headers_bit_url="http://kernel.ubuntu.com/~kernel-ppa/mainline/v${required_version}/${headers_bit_name}"
+
+echo -ne "\n  ${bold}安装 ${green}$required_version${jiacu} headers_all ... ${normal}"
+wget -qO headers1.deb $headers_all_url || { echo -e "\n  ${red}错误${jiacu} headers_all 下载失败！${normal}\n" ; exit 1 ; }
+dpkg -i headers1.deb || { echo -e "\n  ${red}错误${jiacu} headers_all 安装失败！${normal}\n" ; exit 1 ; }
+
+echo -ne "\n  ${bold}安装 ${green}$required_version${jiacu} headers ... ${normal}"
+wget -qO headers2.deb $headers_bit_url || { echo -e "\n  ${red}错误${jiacu} headers 下载失败！${normal}\n" ; exit 1 ; }
+dpkg -i headers2.deb || { echo -e "\n  ${red}错误${jiacu} headers_all 安装失败！${normal}\n" ; exit 1 ; }
+rm headers1.deb headers2.deb ; }
+
+
+
 
 
 
@@ -619,7 +678,7 @@ sysctl -p > /dev/null 2>&1 ; }
 
 # 删除其他内核，并更新引导
 function _delete_kernel() {
-echo -e "\n  ${bold}卸载多余内核 ... ${normal}\n"
+echo -e "\n  ${bold}卸载多余内核及其头文件 ... ${normal}\n"
 kernel_total=` dpkg -l | grep -E linux-[image,headers] | awk '{print $2}' | grep -v "${kernel_version}" | wc -l `
 
 for ddd in debconf-set-selections debconf-get-selections ; do
@@ -628,7 +687,7 @@ for ddd in debconf-set-selections debconf-get-selections ; do
 if [ $kernel_total > 1 ]; then
     for (( integer = 1 ; integer <= ${kernel_total} ; integer++ )) ; do
         kernel_tobe_del=` dpkg -l | grep -E linux-[image,headers] | awk '{print $2}' | grep -v "${kernel_version}" | head -${integer} `
-        echo -ne "  Removing ${kernel_tobe_del} ... "
+        echo -ne "Removing ${kernel_tobe_del} ... "
         echo `debconf-get-selections ${deb_del} | grep removing-running-kernel | grep $running_kernel | sed s/true/false/` | debconf-set-selections
         DEBIAN_FRONTEND=noninteractive apt-get -y purge $kernel_tobe_del > /dev/null 2>&1 && echo "$(tput setaf 2)DONE$(tput sgr0)" || echo "$(tput setaf 1)FAILED$(tput sgr0)"
     done
@@ -636,9 +695,6 @@ fi
 
 echo -ne "\n  ${bold}更新引导 ...  "
 update-grub > /dev/null 2>&1 && echo "${green}完成${normal}" ; }
-
-
-
 
 
 
@@ -665,6 +721,8 @@ systemctl start rc-local ; }
 
 
 
+# 询问是否继续（重启版）
+function _ask_continue2() { echo -ne "\n${bold}输入 ${bailvse}回车${jiacu} 继续，完成后会直接重启；按 ${baihongse}Ctrl+C${jiacu} 退出${normal}" ; read response ; echo ; }
 
 
 
@@ -672,4 +730,3 @@ systemctl start rc-local ; }
 cp -f /etc/default/grub "/etc/default/grub.bak.$(date "+%Y.%m.%d.%H.%M.%S")"
 _menu
 _read_response
-
